encoding: utf-8

# SEOç›¸å…³ä¿¡æ¯
title: Mushrooms11s Blog
description: 95åç¨‹åºç¾Šçš„æˆé•¿ã€æ‹çˆ±å² ã€‚ æ“…é•¿:ğŸ„æœºå™¨çå­¦ğŸ„æ•°æ®æ©åŸ‹ğŸ„æ¨¡å¼æ··æ·†ğŸ„äººå·¥æ™ºéšœğŸ„æ·±åº¦é—å¿˜ğŸ„ç¥ç»æ‰çº¿ğŸ„è®¡ç®—æœºå¹»è§‰
keywords: Mushrooms11s,Blog,æ‚Ÿç©ºè˜‘è‡ç¾Š,Java,Html,JavaScript
author: 11
footerText: 'Mushrooms11s Blog'

# è¿™äº›ä¸è¦åŠ¨
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
exclude: ['CNAME', 'README.md', 'LICENSE', 'build']

# åŸŸåé…ç½®
# baseUrlé…ç½®,å¦‚æœç½‘ç«™éƒ¨ç½²åœ¨æ ¹ç›®å½•ä¸‹çš„å…¶ä»–ç›®å½•ä¸­ï¼Œè¯·è®¾ç½®ä¸º /ç›®å½•å
domainUrl: 'http://www.mushrooms11s.com'
baseUrl: ''

# åä¸ªæ§½åœ°å€ï¼Œä¼šåœ¨chaté¡µé¢ä¸­é‡å®šå‘åˆ°è¯¥åœ°å€
tucaoUrl: https://www.baidu.com

# èœå•
menu:
  - title: é¦–é¡µ
    url: /
  - title: å½’ç±»
    url: /pages/categories.html
  - title: æœç´¢
    url: /pages/search.html
  - title: å‹é“¾
    url: /pages/links.html
  - title: ç•™è¨€
    url: /pages/chat.html
  - title: å…³äº
    url: /pages/about.html

# è‡ªå®šä¹‰æ’ä»¶
# plugin-mta-stats
# è…¾è®¯ç§»åŠ¨åˆ†æ(https://mta.qq.com)ï¼Œå¦‚æœéœ€è¦è¯·ç”³è¯·è‡ªå·±çš„ï¼Œä¸éœ€è¦çš„è¯ use è¯·è®¾ç½®ä¸º false
# plugin-baidu-push
# ç™¾åº¦æ”¶å½•è‡ªåŠ¨æ¨é€ï¼Œä¸éœ€è¦çš„è¯ use è¯·è®¾ç½®ä¸º false
# plugin-click-effect
# é¡µé¢ç‚¹å‡»ï¼Œå‡ºç°æ ¸å¿ƒä¸»ä¹‰ä»·å€¼è§‚
# plugin-mathjax
# æ•°å­¦å…¬å¼æ”¯æŒï¼Œæ¯”è¾ƒå½±å“åŠ è½½é€Ÿåº¦ï¼Œè¯·è®¾ç½®ä¸º false
customPlugins:
  - use: true
    file: 'plugin-mta-stats.html'
    sid: 500581966
    cid: 500581972
  - use: true
    file: 'plugin-baidu-push.html'
  - use: true
    file: 'plugin-click-effect.html'
  - use: false
    file: 'plugin-mathjax.html'

# å‹æƒ…é“¾æ¥
links:
  - title: TMaizeçš„ä¸ªäººåšå®¢
    url: http://blog.tmaize.net
  - title: lhw blog
    url: https://gateway.pinata.cloud/ipns/blog.lhwcrt.top/